# Generated by Django 3.2.10 on 2022-01-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0004_auto_20200704_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='object_pk',
            field=models.UUIDField(verbose_name='object ID'),
        ),
    ]
